####################################################################################################################
#
#   FreemodeEvents configuration
#   Plugin by Jamboxman5
#
####################################################################################################################

#
# Global Configuration
#

# Cooldown between events in seconds.
event-cooldown: 60

####################################################################################################################

#
# Chat Event Configuration
#

### Unscramble Configuration

# Unscramble selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
unscramble-weight: 1

# Unscramble time limit in seconds.
unscramble-timer: 15

# Unscramble difficulty (0 - Easy, 1 - Hard, 2 - Random)
# Easy mode retains the first and last character, and only randomizes those between.
unscramble-difficulty: 0

# Unscramble difficulty randomizer (Between 0.0 - 1.0)
# Percent chance of an event using hard mode. 0.5 means there's a 50% chance of the event using hard mode.
unscramble-difficulty-chance: 0.5

# Unscramble event phrases.
unscramble-phrases:
  - SpigotMC
  - Jamboxman5
  - SlickNick73
  - Tombo870
  - Minecraft
  - JahCraft
  - TownyPlus
  - WesternHunting
  - WesternBounties

####################################################################################################################

#
# Challenge Event Configuration
#

### Rampage Configuration

# Rampage selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
rampage-weight: 1

# Rampage time limit in seconds.
rampage-timer: 180

# Number of kills required to complete the rampage
# Set to -1 to remove the limit and award highest kill count
rampage-target: -1

# Mob types which will count toward progression when killed for rampage events.
# Acceptable values can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Must be a valid mob; no armor stands or effect clouds.
rampage-mobs:
  - ZOMBIE
  - SKELETON
  - SPIDER
  - HUSK
  - STRAY
  - ENDERMAN
  - CAVE_SPIDER
  - BLAZE
  - SLIME
  - CREEPER

