####################################################################################################################
#
#   FreemodeEvents configuration
#   Plugin by Jamboxman5
#
####################################################################################################################

#
# Global Configuration
#

# Cooldown between events in seconds.
event-cooldown: 300



####################################################################################################################

#
# Chat Event Configuration
#

### Unscramble Configuration

# Unscramble selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
unscramble-weight: 1

# Unscramble time limit in seconds.
unscramble-timer: 15

# Unscramble difficulty (0 - Easy, 1 - Hard, 2 - Random).
# Easy mode retains the first and last character, and only randomizes those between.
unscramble-difficulty: 0

# Unscramble difficulty randomizer (Between 0.0 - 1.0).
# Percent chance of an event using hard mode. 0.5 means there's a 50% chance of the event using hard mode.
unscramble-difficulty-chance: 0.5

# Unscramble event phrases.
unscramble-phrases:
  - SpigotMC
  - Jamboxman5
  - SlickNick73
  - Tombo870
  - Minecraft
  - JahCraft
  - TownyPlus
  - WesternHunting
  - WesternBounties



### Trivia Configuration

# Trivia selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
trivia-weight: 1

# Trivia time limit in seconds.
trivia-timer: 15

# Questions which may be asked.
trivia-questions:
  - question: "Who created Minecraft?"
    answers:
      - "Notch"
      - "jeb_"
      - "Dinnerbone"
      - "Grum"
    correct: "Notch"

  - question: "When was Minecraft Java Edition officially released?"
    answers:
      - "2009"
      - "2011"
      - "2012"
      - "2013"
    correct: "2011"

  - question: "Who is the developer of this plugin?"
    answers:
      - "Jamboxman5"
      - "SlickNick73"
      - "Notch"
      - "jeb_"
    correct: "Jamboxman5"



####################################################################################################################

#
# Challenge Event Configuration
#

### Rampage Configuration

# Rampage selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
rampage-weight: 1

# Rampage time limit in seconds.
rampage-timer: 180

# Number of kills required to complete the rampage.
# Set to -1 to remove the limit and award highest kill count.
rampage-target: -1

# Mob types which will count toward progression when killed for rampage events.
# Acceptable values can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Must be a valid mob; no armor stands or effect clouds.
rampage-mobs:
  - ZOMBIE
  - SKELETON
  - SPIDER
  - HUSK
  - STRAY
  - ENDERMAN
  - CAVE_SPIDER
  - BLAZE
  - SLIME
  - CREEPER



### Gravity Strike Configuration

# Gravity Strike selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
gravity-strike-weight: 1

# Gravity Strike time limit in seconds.
gravity-strike-timer: 180

# Distance required to complete the challenge.
# Set to -1 to remove the limit and award the highest fall.
gravity-strike-target: -1

# Require mace for the hit to count
gravity-strike-require-mace: false



### Kill List Configuration

# Kill List selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
kill-list-weight: 1

# Kill List time limit in seconds.
kill-list-timer: 180

# Kill List size.
# Number of mob types to be selected for an event instance.
# If this number is smaller than the eligible mobs list it will default to the full list.
kill-list-size: 5

# Mob types which are eligible for selection for an instance of Kill List.
# Acceptable values can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Must be a valid mob; no armor stands or effect clouds.
kill-list-mobs:
  - ZOMBIE
  - SKELETON
  - SPIDER
  - HUSK
  - STRAY
  - ENDERMAN
  - CAVE_SPIDER
  - BLAZE
  - SLIME
  - CREEPER



### Sniper Challenge Configuration

# Sniper Challenge selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
sniper-challenge-weight: 1

# Sniper Challenge time limit in seconds.
sniper-challenge-timer: 180

# Distance required to complete the challenge.
# Set to -1 to remove the limit and award the longest snipe.
sniper-challenge-target: -1



### Time to Mine Configuration

# Time to Mine selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
time-to-mine-weight: 1

# Time to Mine time limit in seconds.
time-to-mine-timer: 180

# Blocks required to complete the challenge.
# Set to -1 to remove the limit and award the most blocks.
time-to-mine-target: -1

# Material types which are eligible for selection for an instance of Time to Mine.
# Acceptable values can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Must be a valid block; no items which cannot be placed or can only be placed as entities (boats, item frames, etc.).
time-to-mine-blocks:
  - COAL_ORE
  - IRON_ORE
  - REDSTONE_ORE
  - GOLD_ORE
  - LAPIS_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE



### King of the Castle Event Configuration

# King of the Castle time limit in seconds.
castle-defend-timer: 180

# Start timer upon first entry?
# TRUE: Event time limit doesn't start counting until a player enters the defend zone.
# FALSE: Event time limit starts as soon as the event is triggered.
# If true, the time limit will count in the background and the event will end if nobody enters the zone in time.
castle-defend-entry-start: true

## Locations to be automatically selected from when triggering a King of the Castle event
# Can be manually defined here or set via "/events create kingofthecastle <shape> <radius>", with the
# center of the defense zone being the location at which the command is executed.
castle-defend-locations:

  ## Example locations (You're going to want to remove these / repace them with your own)
  # EXAMPLE LOCATION 1
  # Location Name (location1) (Can be whatever you want - no spaces)
  location1:
    # Defense zone shape. ("square" or "circle")
    shape: square
    # Radius of defense zone. (5 block radius means the zone will be 10 blocks wide at its widest point)
    radius: 5
    # Coordinate locations of the center of the defense zone for this location.
    centerX: 100.0
    centerY: 100.0
    centerZ: 100.0
    # World name in which the event takes place.
    world: world

  # EXAMPLE LOCATION 2
  # Location Name (location1) (Can be whatever you want - no spaces)
  location2:
    # Defense zone shape. ("square" or "circle")
    shape: square
    # Radius of defense zone. (5 block radius means the zone will be 10 blocks wide at its widest point)
    radius: 10
    #Coordinate locations of the center of the defense zone for this location.
    centerX: -200.0
    centerY: 100.0
    centerZ: -200.0
    # World name in which the event takes place.
    world: world

####################################################################################################################

#
# Work Event Configuration
#

## These events are triggered by players using the /work command.

### Executive Search Configuration

# Executive Search time limit in seconds.
executive-search-timer: 180

# Cooldown before a player can start another Executive Search
executive-search-cooldown: 600

# Frequency of location alert sounds in seconds.
executive-search-beep-frequency: 3

# Amount of time the executive can stand still before their location is revealed.
executive-search-afk-limit: 30

# Radius of the search zone in blocks
executive-search-radius: 100



####################################################################################################################

#
# Integration Events Configuration
#

### WesternHunting Events

##  These events are integrations with one of my other plugins, WesternHunting
##  Find it here: https://www.spigotmc.org/resources/westernhunting-wip.130522/
##  They will not work without it and are disabled by default!

### Trapper Challenge (Collect the most animal pelts)

# Trapper Challenge selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
trapper-challenge-weight: 0

# Trapper Challenge time limit in seconds.
trapper-challenge-timer: 180

# Pelts required to complete the challenge.
# Set to -1 to remove the limit and award the most blocks.
trapper-challenge-target: -1

# Require 3-star pelts for progression? (true/false)
trapper-challenge-require-perfect: false



### Bass Pros (Collect the most animal pelts)

# Bass Pros selection weight.
# Larger number -> Higher likelihood of selection when starting an event.
# Set to 0 to disable this type of event.
bass-pros-weight: 0

# Bass Pros time limit in seconds.
bass-pros-timer: 180

# Fish required to complete the challenge.
# Set to -1 to remove the limit and award the most blocks.
bass-pros-target: -1

# Require 3-star fish for progression? (true/false)
bass-pros-require-perfect: false